[project]
name = "poc-generation"
version = "0.1.0"
description = "PoC Generation common dependencies"
requires-python = ">=3.11"
dependencies = [
    "requests",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
